approve_by_comment: true
approve_regex: ':\+1:'
reject_regex: ':\-1:'
reject_value: -1
reset_on_push: true
author_approval: ignored
reviewers:
    -
        name: admins
        required: 1
        members:
            - aramwram
            - mehappens
